/**
 * Builds the HTML for a proctor-requested student report PDF, generated by
 * the Agentic AI chatbot's generate_report_pdf tool. Mirrors the markup
 * conventions of ReportComponent.tsx / weeklyAttendance.service.js's
 * buildAttendanceReportHTML (same CSS classes, injected by
 * generatePDFFromHTML's styled wrapper in email.service.js) so the rendered
 * PDF looks consistent with the rest of the app, but is built server-side
 * from a data object since the agent has no browser to scrape a live DOM
 * from.
 *
 * The proctor-remarks section is only included when proctorRemarksText is
 * given -- omitted entirely (not left blank) when the proctor chose to skip it.
 */
export const buildProctorReportHTML = (student, aiRemark, proctorRemarksText) => {
  const details = student.details || {};
  const subjects = details.subjects || details.current_semester || [];
  const classDetails = details.class_details || "";

  const semMatch = classDetails.match(/SEM\s*(\d+)/i);
  const semester = semMatch ? `Semester ${semMatch[1]}` : classDetails;
  const deptMatch = classDetails.match(/B\.E-(\w+)/i);
  const dept = deptMatch ? deptMatch[1] : "—";

  const rows = subjects
    .map((s, idx) => {
      const attendance = Math.round(s.attendance || 0);
      const isLow = attendance < 75;
      return `
        <tr>
          <td>${idx + 1}</td>
          <td>${s.name || "Unknown Subject"}</td>
          <td ${isLow ? 'class="low-attendance"' : ""} style="text-align:center;">${attendance}%</td>
          <td style="text-align:center;">${s.marks ?? "N/A"} / 50</td>
        </tr>`;
    })
    .join("");

  const noDataRow = `
    <tr>
      <td colspan="4" style="text-align:center; padding:20px; color:#94a3b8;">
        No academic data available for the current semester.
      </td>
    </tr>`;

  const escapeHtml = (str) =>
    String(str)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");

  const aiRemarkHtml = (aiRemark || "")
    .split(/\n{2,}/)
    .map((para) => `<p>${escapeHtml(para).replace(/\n/g, "<br/>")}</p>`)
    .join("");

  const proctorRemarksSection = proctorRemarksText
    ? `
      <div class="editable-remarks-container">
        <h4>Proctor Remarks</h4>
        <div class="tiptap-editor-container">
          <div class="tiptap-content">
            ${(proctorRemarksText || "")
              .split(/\n{2,}/)
              .map((para) => `<p>${escapeHtml(para).replace(/\n/g, "<br/>")}</p>`)
              .join("")}
          </div>
        </div>
      </div>`
    : "";

  return `
    <div id="report-sheet" class="a4-sheet">
      <header class="sheet-header">
        <div class="college-logo">
          <img src="/logo.png" alt="MSRIT Logo" class="college-logo-img" />
        </div>
        <div class="college-info">
          <h1>M S RAMAIAH INSTITUTE OF TECHNOLOGY</h1>
          <h2>Academic Performance Report</h2>
          <p class="student-meta">
            USN: ${student.usn} &nbsp;|&nbsp; ${semester} &nbsp;|&nbsp; Dept: ${dept} &nbsp;|&nbsp; CGPA: ${details.cgpa ?? "—"}
          </p>
          <p class="student-meta" style="font-weight:600;">${student.name || ""}</p>
        </div>
      </header>

      <hr class="divider" />

      <section class="table-section">
        <h3>Current Semester Performance</h3>
        <table class="marks-table">
          <thead>
            <tr>
              <th> </th>
              <th>Subject Name</th>
              <th>Attendance (%)</th>
              <th>Score (CIE)</th>
            </tr>
          </thead>
          <tbody>
            ${rows.length > 0 ? rows : noDataRow}
          </tbody>
        </table>
      </section>

      <section class="remarks-section">
        <div class="editable-remarks-container">
          <h4>System Generated Remarks</h4>
          <div class="tiptap-editor-container">
            <div class="tiptap-content">${aiRemarkHtml}</div>
          </div>
        </div>

        ${proctorRemarksSection}
      </section>

      <footer class="sheet-footer">
        <div class="footer-meta">
          <small>Generated: ${new Date().toLocaleString()}</small>
          <small>MSR Insight — Agentic AI Report</small>
        </div>
      </footer>
    </div>
  `;
};
