/**
 * Builds the HTML for a proctor-requested student report PDF, generated by
 * the Agentic AI chatbot's generate_report_pdf tool. Mirrors the markup
 * conventions of ReportComponent.tsx / weeklyAttendance.service.js's
 * buildAttendanceReportHTML (same CSS classes, injected by
 * generatePDFFromHTML's styled wrapper in email.service.js) so the rendered
 * PDF looks consistent with the rest of the app, but is built server-side
 * from a data object since the agent has no browser to scrape a live DOM
 * from.
 *
 * The proctor-remarks section is only included when proctorRemarksText is
 * given -- omitted entirely (not left blank) when the proctor chose to skip it.
 */
export const buildProctorReportHTML = (student, aiRemark, proctorRemarksText) => {
  const details = student.details || {};
  const subjects = details.subjects || details.current_semester || [];
  const classDetails = details.class_details || "";

  const semMatch = classDetails.match(/SEM\s*(\d+)/i);
  const semester = semMatch ? `Semester ${semMatch[1]}` : classDetails;
  const deptMatch = classDetails.match(/B\.E-(\w+)/i);
  const dept = deptMatch ? deptMatch[1] : "—";

  const rows = subjects
    .map((s, idx) => {
      // A subject with no classes held yet (e.g. Mini Project, Physical
      // Education early in the semester) has present=absent=0, which the
      // scraper stores as a 0% attendance -- indistinguishable from actually
      // missing every class unless we check the held-class count ourselves.
      // Treat 0 held classes as 100% (nothing missed) rather than flagging it.
      const ad = s.attendance_details || {};
      const held = (ad.present || 0) + (ad.absent || 0);
      const attendance = held > 0 ? Math.round(s.attendance || 0) : 100;
      const isLow = held > 0 && attendance < 75;
      // Inline style on just this cell rather than a "low-attendance" class:
      // the shared CSS's tr.low-attendance rule expects the class on the
      // <tr>, which would also redden the marks cell in this 4-column table
      // (unlike the 3-column weekly-attendance report it was written for).
      const attendanceStyle = isLow
        ? "text-align:center; background:#fee2e2; color:#991b1b; font-weight:600;"
        : "text-align:center;";

      // marks === 0 whenever every assessment component (T1, T2, AQ1, AQ2)
      // is itself 0, by construction of the total-marks formula
      // (dataNormalizer.js: avg(T1,T2) + AQ1 + AQ2) -- indistinguishable
      // from "not graded yet" in the data we're given (the scraper's
      // eligibility/max_marks markers that could disambiguate this don't
      // survive normalization). Treat 0 as ungraded and skip coloring, same
      // call as the attendance fix above.
      const marks = typeof s.marks === "number" ? s.marks : null;
      let marksStyle = "text-align:center;";
      if (marks !== null && marks > 0) {
        if (marks < 21) {
          marksStyle = "text-align:center; background:#fee2e2; color:#991b1b; font-weight:600;";
        } else if (marks <= 30) {
          marksStyle = "text-align:center; background:#fef9c3; color:#854d0e; font-weight:600;";
        }
      }

      return `
        <tr>
          <td>${idx + 1}</td>
          <td>${s.name || "Unknown Subject"}</td>
          <td style="${attendanceStyle}">${attendance}%</td>
          <td style="${marksStyle}">${marks ?? "N/A"} / 50</td>
        </tr>`;
    })
    .join("");

  const noDataRow = `
    <tr>
      <td colspan="4" style="text-align:center; padding:20px; color:#94a3b8;">
        No academic data available for the current semester.
      </td>
    </tr>`;

  const escapeHtml = (str) =>
    String(str)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");

  const aiRemarkHtml = (aiRemark || "")
    .split(/\n{2,}/)
    .map((para) => `<p>${escapeHtml(para).replace(/\n/g, "<br/>")}</p>`)
    .join("");

  const proctorRemarksSection = proctorRemarksText
    ? `
      <div class="editable-remarks-container">
        <h4>Proctor Remarks</h4>
        <div class="tiptap-editor-container">
          <div class="tiptap-content">
            ${(proctorRemarksText || "")
              .split(/\n{2,}/)
              .map((para) => `<p>${escapeHtml(para).replace(/\n/g, "<br/>")}</p>`)
              .join("")}
          </div>
        </div>
      </div>`
    : "";

  return `
    <style>
      /* Scoped to this report only -- tighter than the shared .marks-table/
         .tiptap-content defaults so a full subject list (up to ~10-12
         subjects) plus remarks still fits on one A4 page instead of
         spilling a mostly-empty second page. */
      /* The shared wrapper forces .a4-sheet to a flat 1123px min-height
         regardless of actual content -- combined with its own outer
         padding, that alone already exceeds one printable A4 page, so a
         report this short would spill onto a near-empty second page no
         matter how compact the content below is. This report's content is
         well under a page, so let the box size to it instead. */
      #report-sheet.a4-sheet { padding: 24px 40px; min-height: 0; }
      #report-sheet .sheet-header { margin-bottom: 8px; }
      #report-sheet .college-logo-img { height: 56px; }
      #report-sheet .divider { margin: 4px 0 12px 0; }
      #report-sheet .table-section { margin-bottom: 14px; }
      #report-sheet .table-section h3 { margin-bottom: 6px; }
      #report-sheet .marks-table th,
      #report-sheet .marks-table td { padding: 5px 10px; font-size: 0.72rem; }
      #report-sheet .remarks-section { gap: 10px; }
      #report-sheet .editable-remarks-container h4 { margin-bottom: 4px; font-size: 0.72rem; }
      #report-sheet .tiptap-content { padding: 8px; min-height: 0; font-size: 0.76rem; }
      #report-sheet .tiptap-content p { line-height: 1.4; margin-bottom: 4px; }
      #report-sheet .sheet-footer { margin-top: 16px; padding-top: 10px; }
    </style>
    <div id="report-sheet" class="a4-sheet">
      <header class="sheet-header">
        <div class="college-logo">
          <img src="/logo.png" alt="MSRIT Logo" class="college-logo-img" />
        </div>
        <div class="college-info">
          <h1>M S RAMAIAH INSTITUTE OF TECHNOLOGY</h1>
          <h2>Academic Performance Report</h2>
          <p class="student-meta">
            USN: ${student.usn} &nbsp;|&nbsp; ${semester} &nbsp;|&nbsp; Dept: ${dept} &nbsp;|&nbsp; CGPA: ${details.cgpa ?? "—"}
          </p>
          <p class="student-meta" style="font-weight:600;">${student.name || ""}</p>
        </div>
      </header>

      <hr class="divider" />

      <section class="table-section">
        <h3>Current Semester Performance</h3>
        <table class="marks-table">
          <thead>
            <tr>
              <th> </th>
              <th>Subject Name</th>
              <th>Attendance (%)</th>
              <th>Score (CIE)</th>
            </tr>
          </thead>
          <tbody>
            ${rows.length > 0 ? rows : noDataRow}
          </tbody>
        </table>
      </section>

      <section class="remarks-section">
        <div class="editable-remarks-container">
          <h4>System Generated Remarks</h4>
          <div class="tiptap-editor-container">
            <div class="tiptap-content">${aiRemarkHtml}</div>
          </div>
        </div>

        ${proctorRemarksSection}
      </section>

      <footer class="sheet-footer">
        <div class="footer-meta">
          <small>Generated: ${new Date().toLocaleString()}</small>
          <small>MSR Insight — Agentic AI Report</small>
        </div>
      </footer>
    </div>
  `;
};
